---
default:
  image: ${CONTAINER_REGISTRY}/${CONTAINER_DEFAULT}

variables:
  GIT_STRATEGY: clone

# Generic "fetch the environment" task to facilitate future
# debugging activities
get-vars:
  needs: []
  stage: .pre
  script:
    - export

# Lint any YAML-based content to ensure we don't pollute the project
# any time we add or update YAML-based content
lint-yaml:
  needs:
    - get-vars
  before_script:
    - bash scripts/ci-setup/install_py3.sh
    - bash scripts/ci-setup/install_pymod.sh yamllint
  script:
    - bash scripts/lint-yaml.sh

# Lint any shell-based content to ensure we don't pollute the projct
# any time we add or update shell-based content
lint-shell:
  needs:
    - get-vars
  before_script:
    - bash scripts/ci-setup/install_py3.sh
    - bash scripts/ci-setup/install_pymod.sh shellcheck-py
  script:
    - bash scripts/lint-shell.sh
...
